version: '3.8'

services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "My Org"
      LDAP_DOMAIN: "163.53.203.3"
      LDAP_ADMIN_PASSWORD: pankaj4433
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    ports:
      - "6443:443"
    depends_on:
      - ldap

  flask:
    build:
      context: .
    ports:
      - "5010:5000"
    volumes:
      - .:/app
    depends_on:
      - ldap

volumes:
  ldap_data:
  ldap_config:
